#!/bin/sh

echo "[pre-push] linting..."

npm run format-check

if [ $? -ne 0 ]; then
	echo "❌ Lint errors found. try to fix them by running 'npm run format'\n"
    exit 1
fi

echo "✅ Lint checks passed!"
exit 0
